### ISSUE TITLE
Implement Eiger detector data format parsing

### ISSUE THREAD

**Issue by kj18vish** [biochem-fan/eiger2cbf#11]
Hi, I am very new to programing in general and ran into this issue with using eiger2cbf. I am trying to convert the master .h5 file from the FMX beamline at brookhaven which has an eiger 16M detector. Below is the meta data when I try running any of the commands:

(base) kimberlyvish@TB285-03 20-11-3 % eiger2cbf 20-11_15712_master.h5 out.cbf
Traceback (most recent call last):             ]  25%  20-11_15712_master.h5
  File "/Users/kimberlyvish/Desktop/ENTER/bin/eiger2cbf", line 8, in <module>
    sys.exit(main())
  File "/Users/kimberlyvish/Desktop/ENTER/lib/python3.8/site-packages/fabio/app/eiger2cbf.py", line 524, in main
    succeeded = convert_all(args)
  File "/Users/kimberlyvish/Desktop/ENTER/lib/python3.8/site-packages/fabio/app/eiger2cbf.py", line 414, in convert_all
    finish_at = convert_one(filename, options, start_at)
  File "/Users/kimberlyvish/Desktop/ENTER/lib/python3.8/site-packages/fabio/app/eiger2cbf.py", line 306, in convert_one
    raise NotImplementedError("Please implement Eiger detector data format parsing or at least open an issue")
NotImplementedError: Please implement Eiger detector data format parsing or at least open an issue
(base) kimberlyvish@TB285-03 20-11-3 % 

Any help will be greatly appriciated!

**Comment by biochem-fan** [comment]
Yours is eiger2cbf from fabio, which is a completely different project.
The name is identical just by a coincidence.
Please report it to them https://github.com/silx-kit/fabio/blob/main/src/fabio/app/eiger2cbf.py.
